#! /bin/sh

# Workspaces
bspc monitor -d         

#█▓▒░ randomly set theme on load
img=$(find ~/theme/themes/*.crop.jpg -printf "%f\n" | shuf -n1)
~/theme/theme-set.sh $img

#█▓▒░ Programs
killall -9 sxhkd compton polybar
sxhkd &
polybar --reload laptop &
compton & 

# Layout
bspc config border_width         4
bspc config window_gap           24

bspc config top_padding 40
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config focus_follows_pointer true

# █▓▒░ Window Layout
bspc config split_ratio           0.50

# █▓▒░ Rules
bspc rule -a Emacs state=tiled

